import type React from "react"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./new-globals02.css" // ここを修正しました。globals.cssのインポートを削除しました。
import { ThemeProvider } from "@/components/theme-provider"
import LenisSetup from "@/components/lenis-setup"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
    generator: 'v0.dev'
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          {children}
          <LenisSetup />
        </ThemeProvider>
      </body>
    </html>
  )
}
